### PR TITLE
Fixing the autoselect and factory repair issue

### PR DESCRIPTION
**Pull request by ghost**
This should fix Issue #57 along with preventing the factory for needlessly running the repair recipe whenever not at full health, just because it has the resources to do so.

This changes AutoSelect to only run the Repair recipe if the factory is in disrepair.

### CODE REVIEW

**Comment by Diet-Cola** [comment]
Will add this to test later, I made a similar thing for 1.17 but we can just use this

**Comment by Diet-Cola** [comment]
On test

**Comment by wingzero54** [comment]
@Diet-Cola do you remember if this is good to go or does it need more testing?

**Comment by wingzero54** [comment]
@EvilAsuramaru this will need to be updated to latest FactoryMod please, it has a minor conflict now

**Pull request closed without merging**
